### ISSUE TITLE
Local attention

### ISSUE THREAD

**Issue by jeammimi** [datalogue/keras-attention#12]
Hi, first thanks a lot for the tutorial and the code that work right away!
In my case during the training I have sequence of well defined length,
but when I apply the model I work with sequences from size 100 to 100000.
So one problem is that the timestep is encoded in hard in the AttentionEncoder.
I could rebuild the model each time that I apply it but it is a bit heavy.

So one option would be to change the code to make it independent of the self.timesteps .
Another one would be to put a hardcoded window of fixed length, because I don't expect 
a dependency larger than 10 to 20 letters around any given step.

what do you think will be the easiest / more interesting ?

Thanks

**Comment by jeammimi** [comment]
An other question: Is this really necessary to add an LSTM cell to the attention layer:
If I understand correctly, the context vector could be used as output of this layer no?

**Comment by zafarali** [comment]
Yes, In theory you could return any part of the internals as you want. From
my understanding? The LSTM helps the model have a longer term dependence on
time. As for changing the output sequence length, it’s definitely possible,
i think you’d have to edit the code for call() if I’m not mistaken. It’s
also likely that there are neater ways of doing this.

**Comment by zafarali** [comment]
You could also pad the input sequence so that it is as long as the average
output sequence this way you can generate longer. Just a hack for our
static computation graphs.

**Comment by jeammimi** [comment]
I manage to make it work without fixed length by changing two lines:
`_stm = K.repeat(stm, K.shape(self._uxpb)[1])`
and:
`at_sum_repeated = K.repeat(at_sum, K.shape(self._uxpb)[1])`

But for now I trained it with length of 20 and apply it to longer sequences and it does not
seems to work well. But I have to investigate why

Thanks
