### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by basma-b** [datalogue/keras-attention#18]
https://github.com/datalogue/keras-attention/blob/693f9516a5f752a0c002d0ccc2184c663de0fdb3/data/reader.py#L146

File fake.csv is missing, can you provide it please ?

**Comment by zafarali** [comment]
Thanks for raising this issue, I think that is a remnant of some test code i was running. You can use something like this and it should work:
```
“Tuesday 4th January 2018”, “2018-01-04”
“Feb 8 1994”, “1994-02-08”
```

Hope this helps.
