### ISSUE TITLE
How to use AttentionDecoder after adding embedding layer?

### ISSUE THREAD

**Issue by leoliao0129** [datalogue/keras-attention#22]
Hi,
I'm trying to use your AttentionDecoder, but get stuck after adding embedding layer.
I've used tokenizer and  pad_sequences to encode each doc (total number is 100) and its corresponding label (ytrain below), and actually what I want to try is echo partial sequence in each doc.

The shape of input data looks like:

> Xtrain.shape = (100, 148)

> ytrain.shape = (100, 148) -> this is the partial sequence of Xtrain
 
This is how I build the model:
```
model = Sequential()
model.add(Embedding(vocab_size, 150, input_length=max_length))
model.add(Bidirectional(LSTM(150, return_sequences=True)))
model.add(AttentionDecoder(150, n_features)) # n_features = vocab_size
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
model.summary()
model.fit(Xtrain, ytrain, epochs=epochs, verbose=1)
```

But it throws me an error:

> ValueError: Error when checking target: expected AttentionDecoder to have 3 dimensions, but got array with shape (100, 148)

Can you tell me how to solve it? Thank you very much.

**Comment by zafarali** [comment]
Your Y is not correctly formed, it needs to be an array of size `(?, input_length, n_features)`

The following works without issue:

```
model = Sequential()
model.add(Embedding(input_vocab.size(), 150, input_length=5))
model.add(Bidirectional(LSTM(150, return_sequences=True)))
model.add(AttentionDecoder(150, output_vocab.size()))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
model.summary()
```

and training using outputs from `Data` and `Vocabulary` in the repo

**Comment by dcabz** [comment]
@zafarali  the model is taking too long to compile by adding the attention decoder
