### ISSUE TITLE
new keras version

### ISSUE THREAD

**Issue by hitxujian** [datalogue/keras-attention#23]
in the new keras version,for example  2.1.3  
![image](https://user-images.githubusercontent.com/11830865/35435730-c029d952-02c6-11e8-9075-c812aa47f56d.png)
class Recurrent is in the legacy package,
is this means that it't bettter implements RNN class instead of Recurrent?
class AttentionDecoder(Recurrent):
class AttentionDecoder(RNN):

**Comment by zafarali** [comment]
The code here was written before the update from `Recurrent` to `RNN`. I believe that they are handled differently now (i.e. `RNN` uses objects called `RNNCells` which are applied at every time step) My implementation here does all of this in one class and may not work. However, if you want to take a shot at converting it please do go ahead! It could potentially solve the issues seen in #15

**Comment by hitxujian** [comment]
thanks,i will try
