### ISSUE TITLE
How to apply beam search ?

### ISSUE THREAD

**Issue by RobrechtM** [datalogue/keras-attention#41]
I want to apply beam search to the decoder, as described [here](https://hackernoon.com/beam-search-a-search-strategy-5d92fb7817f). This requires some changes to the decoder but I can't figure out where. Any ideas?

**Comment by zafarali** [comment]
You should be able to implement beam search here: 
https://github.com/datalogue/keras-attention/blob/856dbe66490a73c55dcfdc2f793aea6c7307b530/utils/examples.py#L8

**Comment by robrechtme** [comment]
I understand that you can change the `argmax` there, but you still need to calculate _P(Y2 | X, Y1)_ for the k best _Y1_ predictions, right? In order to calculate that, you need to feed _Y1_ into the decoder, or am I completely wrong here?

**Comment by zafarali** [comment]
I dont think you do. See here:
https://machinelearningmastery.com/beam-search-decoder-natural-language-processing/
