### ISSUE TITLE
about lstm layer numer

### ISSUE THREAD

**Issue by hitxujian** [datalogue/keras-attention#5]
hi:
thanks for sharing!
given the code
 **rnn_encoded = Bidirectional(LSTM(encoder_units, return_sequences=True),
                                name='bidirectional_1',
                                merge_mode='concat',
                                trainable=trainable)(input_embed)**
 is this code means that  LSTM only haven one hidden layer and the size is specified by encoder_units?
if so how to  add more hidden layers?

**Comment by zafarali** [comment]
Hi there!

The `encoder_units` parameter sets the size of the _hidden state_ that is being returned by the LSTM (Btw, the BLSTM with `merge=concat` will return `2*encoder_units`). So yes, in the loose interpretation of _hidden layer_.

To add more LSTM layers on top of each other you are probably referring to [stacked LSTMs](https://keras.io/getting-started/sequential-model-guide/#stacked-lstm-for-sequence-classification) you can see an example of implementation here: fchollet/keras#3522 and [here](https://keras.io/getting-started/sequential-model-guide/#stacked-lstm-for-sequence-classification)

Let me know if you have more questions!

**Comment by hitxujian** [comment]
thanks
