### ISSUE TITLE
Problem loading sample weights

### ISSUE THREAD

**Issue by vgoklani** [datalogue/keras-attention#6]
I received an error when trying to load your saved weights:

    padding = 50
    weights = "weights/NMT.49-0.01.hdf5"
    weights_file = os.path.expanduser(weights)
    viz = Visualizer(padding=padding)
    pred_model = simpleNMT(trainable=False,
                           pad_length=padding,
                           n_chars=viz.input_vocab.size(),
                           n_labels=viz.output_vocab.size())
    pred_model.load_weights(weights_file, by_name=True)

Here's the error:

     ---------------------------------------------------------------------------
    InvalidArgumentError                      Traceback (most recent call last)
    /opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py in _call_cpp_shape_fn_impl(op, input_tensors_needed, input_tensors_as_shapes_needed, debug_python_shape_fn, require_shape_fn)
        670           graph_def_version, node_def_str, input_shapes, input_tensors,
    --> 671           input_tensors_as_shapes, status)
        672   except errors.InvalidArgumentError as err:

    /opt/conda/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
         88             try:
    ---> 89                 next(self.gen)
         90             except StopIteration:

    /opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in raise_exception_on_not_ok_status()
        465           compat.as_text(pywrap_tensorflow.TF_Message(status)),
    --> 466           pywrap_tensorflow.TF_GetCode(status))
        467   finally:

    InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1367 and 1426 for 'Assign' (op: 'Assign') with input shapes: [1367,1024], [1426,1024].

    During handling of the above exception, another exception occurred:

    ValueError                                Traceback (most recent call last)
    <ipython-input-6-4acc701a7fe8> in <module>()
          7                        n_chars=viz.input_vocab.size(),
          8                        n_labels=viz.output_vocab.size())
    ----> 9 pred_model.load_weights(weights_file, by_name=True)

    /opt/conda/lib/python3.6/site-packages/keras/engine/topology.py in load_weights(self, filepath, by_name)
       2568             f = f['model_weights']
       2569         if by_name:
    -> 2570             load_weights_from_hdf5_group_by_name(f, self.layers)
       2571         else:
       2572             load_weights_from_hdf5_group(f, self.layers)

    /opt/conda/lib/python3.6/site-packages/keras/engine/topology.py in load_weights_from_hdf5_group_by_name(f, layers)
       3109                 weight_value_tuples.append((symbolic_weights[i],
       3110                                             weight_values[i]))
    -> 3111     K.batch_set_value(weight_value_tuples)

    /opt/conda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in batch_set_value(tuples)
       2181                 assign_placeholder = tf.placeholder(tf_dtype,
       2182                                                     shape=value.shape)
    -> 2183                 assign_op = x.assign(assign_placeholder)
       2184                 x._assign_placeholder = assign_placeholder
       2185                 x._assign_op = assign_op

    /opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/variables.py in assign(self, value, use_locking)
        514       the assignment has completed.
        515     """
    --> 516     return state_ops.assign(self._variable, value, use_locking=use_locking)
        517 
        518   def assign_add(self, delta, use_locking=False):

    /opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py in assign(ref, value, validate_shape, use_locking, name)
        269     return gen_state_ops.assign(
        270         ref, value, use_locking=use_locking, name=name,
    --> 271         validate_shape=validate_shape)
        272   return ref.assign(value)

    /opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py in assign(ref, value, validate_shape, use_locking, name)
         43   result = _op_def_lib.apply_op("Assign", ref=ref, value=value,
         44                                 validate_shape=validate_shape,
    ---> 45                                 use_locking=use_locking, name=name)
         46   return result
         47 

    /opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py in apply_op(self, op_type_name, name, **keywords)
        765         op = g.create_op(op_type_name, inputs, output_types, name=scope,
        766                          input_types=input_types, attrs=attr_protos,
    --> 767                          op_def=op_def)
        768         if output_structure:
        769           outputs = op.outputs

    /opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in create_op(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_shapes, compute_device)
       2506                     original_op=self._default_original_op, op_def=op_def)
       2507     if compute_shapes:
    -> 2508       set_shapes_for_outputs(ret)
       2509     self._add_op(ret)
       2510     self._record_op_seen_by_control_dependencies(ret)

    /opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in set_shapes_for_outputs(op)
       1871       shape_func = _call_cpp_shape_fn_and_require_op
       1872 
    -> 1873   shapes = shape_func(op)
       1874   if shapes is None:
       1875     raise RuntimeError(

    /opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in call_with_requiring(op)
       1821 
       1822   def call_with_requiring(op):
    -> 1823     return call_cpp_shape_fn(op, require_shape_fn=True)
       1824 
       1825   _call_cpp_shape_fn_and_require_op = call_with_requiring

    /opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py in call_cpp_shape_fn(op, input_tensors_needed, input_tensors_as_shapes_needed, debug_python_shape_fn, require_shape_fn)
        608     res = _call_cpp_shape_fn_impl(op, input_tensors_needed,
        609                                   input_tensors_as_shapes_needed,
    --> 610                                   debug_python_shape_fn, require_shape_fn)
        611     if not isinstance(res, dict):
        612       # Handles the case where _call_cpp_shape_fn_impl calls unknown_shape(op).

    /opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py in _call_cpp_shape_fn_impl(op, input_tensors_needed, input_tensors_as_shapes_needed, debug_python_shape_fn, require_shape_fn)
        674       missing_shape_fn = True
        675     else:
    --> 676       raise ValueError(err.message)
        677 
        678   if missing_shape_fn:

    ValueError: Dimension 0 in both shapes must be equal, but are 1367 and 1426 for 'Assign' (op: 'Assign') with input shapes: [1367,1024], [1426,1024].

    In [ ]:

    ​
  ​#####

I'm using Keras 2.0.6 and tensorflow 1.2.1

Thanks

**Comment by zafarali** [comment]
So I created a file:
```
# test_file.py
import keras
import tensorflow as tf
import os
import sys
from models.NMT import simpleNMT
from visualize import Visualizer
print('python version:', sys.version)
print('keras version:', keras.__version__)
print('tensorflow version:', tf.__version__)
padding = 50
weights = "weights/NMT.49-0.01.hdf5"
weights_file = os.path.expanduser(weights)
viz = Visualizer(padding=padding)
pred_model = simpleNMT(trainable=False,
                       pad_length=padding,
                       n_chars=viz.input_vocab.size(),
                       n_labels=viz.output_vocab.size())
pred_model.load_weights(weights_file, by_name=True)
```

And then I created `__init__.py` into the root folder of the repo (`touch __init__.py`)

```
➜  keras-attention git:(master) ✗ python test_script.py
Using TensorFlow backend.
python version: 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
keras version: 2.0.6
tensorflow version: 1.2.1
2017-07-26 23:19:14.512770: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-26 23:19:14.512790: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-26 23:19:14.512795: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-26 23:19:14.512799: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
inputs shape: (?, ?, 512)
```

Did not have any issues. I'm not sure how to proceed from here. Any ideas?

**Comment by zafarali** [comment]
I was able to reproduce it by first running `cd data; python generate.py` which generates a fresh vocabulary every time you run it. I will push a fix shortly which includes example vocabulary files so that you can run it!
